### PR TITLE
Update `DQM/Integration` unit tests input stremer files after streamers layout update

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all, also updated the `README` file to contain instructions to re-create streamers whenever there is a need for it.
Companion of the `cmssw` PR: https://github.com/cms-sw/cmssw/pull/45231

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/45231

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
