### PR TITLE
Update streamer files for `DQM/Integration` unit tests

### PR DESCRIPTION
**Pull request by mmusich**
This is a companion of PR https://github.com/cms-sw/cmssw/pull/42953.
Goals are:
   * refresh the `streamDQMGPUvsCPU` unit tests files in order to include also Pixel FED errors for `SiPixelPhase1RawDataErrorComparator`;
   * add `streamDQM` file for `sistrip_appror sistrip_approx_dqm_sourceclient-live` unit test;
   * update `README` file

**Note to reviewers: to pass tests this PR needs to be tested with https://github.com/cms-sw/cmssw/pull/42953**

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/42953

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@tjavaid,since you signed also the cmssw PR https://github.com/cms-sw/cmssw/pull/42953, do you have objections to this update of the externals?

**Comment by tjavaid** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
