### PR TITLE
Update DQM-Integration streamer files for `streamDQMGPUvsCPU`

### PR DESCRIPTION
**Pull request by mmusich**
This PR:
   * removes the unused `streamDQMOnlineBeamspot` streamer files for `run346373`;
   * add `streamDQMGPUvsCPU` streamer files for `run369956` in order to use them for https://github.com/cms-sw/cmssw/pull/42542;
   * updates the `README` file coherently.
   
As stated in https://github.com/cms-sw/cmssw/pull/42542 unfortunately the streamer files for `run369956` lack the necessary collections for the Pixel monitoring client (`SiPixelRawDataErroredmDetSetVector_hltSiPixelDigisFromSoA_*_*` and `SiPixelRawDataErroredmDetSetVector_hltSiPixelDigisLegacy_*_*`). I will update this repository later once we have an appropriate set of files from the central DQM team.
   
Cc: @francescobrivio

### CODE REVIEW

**Comment by francescobrivio** [comment]
Looks good to me, thanks Marco!
No objection from my side to remove the unused `streamDQMOnlineBeamspot` streamer files for `run346373`.

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
