### PR TITLE
update data used for the Pixel,ECal,HCal GPU clients for post-alpaka migration in the HLT menu

### PR DESCRIPTION
**Pull request by mmusich**
After the migration of the HLT menu in 2024 to use `alpaka`-based modules for the local reconstruction of the Pixel, Ecal at HLT (see TSG tickets  [CMSHLT-3109](https://its.cern.ch/jira/browse/CMSHLT-3109), [CMSHLT-3125](https://its.cern.ch/jira/browse/CMSHLT-3125)) the naming of the collections in output to the `DQMGPUvsCPU` stream has been updated (see TSG ticket  [CMSHLT-3132](https://its.cern.ch/jira/browse/CMSHLT-3132)). 
This has prompted `cmssw` PRs in order to comply with the changes:
   * https://github.com/cms-sw/cmssw/pull/44934 (for Pixel)
   * https://github.com/cms-sw/cmssw/pull/44675 (for ECAL, see also related TSG ticket [CMSHLT-3139](https://its.cern.ch/jira/browse/CMSHLT-3139))
   
Due to that, the data used in unit tests currently running in IB and PR tests is out-of-synch with the collection names requested by the clients, see e.g. these [logs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-05-14-2300/unitTestLogs/DQM/Integration#/27150).
The purpose of this PR (joint to the companion cmssw PR https://github.com/cms-sw/cmssw/pull/44971) is to update the data used for the tests to a fresher set coming from  run380649 (from Run2024D pp run [OMS link](https://cmsoms.cern.ch/cms/runs/report?cms_run=380649&cms_run_sequence=GLOBAL-RUN), which features the new collection names.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
